version: '2.1'

networks:
  todolist:

volumes:
  pgdata:

services:
  postgres: 
    image: postgres
    container_name: dev-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
    env_file:
      - .env
    restart: always